### ISSUE TITLE
Semantic object placing

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#10]

**Comment by alex-mitrevski** [comment]
The functionality for semantic object placing is implemented in the [`action-execution`](https://github.com/b-it-bots/action-execution/tree/master/action_execution) repository.

In particular, there we have a definition of a so-called [`sort-release` action](https://github.com/b-it-bots/action-execution/blob/master/action_execution/ontology/actions/sort_release.yaml). The execution model for the action is defined [here](https://github.com/b-it-bots/action-execution/blob/master/action_execution/execution_models/sort_release.py); the model samples placing poses on the desired surface and only considers those samples that are closest to objects of the same category. Sampling is obviously not the cleverest option for this, so this is just a temporary implementation until I have a better solution.
