### ISSUE TITLE
Implement Rasa Core.

### ISSUE THREAD

**Issue by PatrickNa** [b-it-bots/mas_domestic_robotics#103]
Rasa Core is foreseen for the processing of conversation. It needs to be implemented into the ROS architecture.

## Context
This component is essential for speech. It is suppose to allow conversation between the robot and humans and is considered as the central unit for managing the verbal and contextual information.

## Expected Behavior
Based on a conversation, certain actions need to be carried out. 

Rasa core needs to be implemented in such a way, that scenarios for the RoboCup competition can be easily implemented.

**Comment by argenos** [comment]
Can you update or close this issue please?

**Comment by PatrickNa** [comment]
Will do. Probably this afternoon.

**Comment by argenos** [comment]
I'll close this for now. If need be, we can open a new issue.
