### ISSUE TITLE
Define Scenario "Find My Mates".

### ISSUE THREAD

**Issue by PatrickNa** [b-it-bots/mas_domestic_robotics#105]
We have prepared the scenario storing groceries already. Now it is time to proceed with the next task and set it up in parallel. The scenario suggested in this issue is the "Find My Mate" scenario.

## Context
The "Find My Mate" scenario is described in the newest rule book of the RoboCup competition (2019). 

## Expected Behavior
Similar to storing groceries a scenario in mdr_robocup_tasks needs to be defined.

**Comment by PatrickNa** [comment]
See #120 for the progress regarding this issue.

**Comment by argenos** [comment]
This issue was solved in dfe82897177ddc096dad040a25198d387688fc0f and further improved in 986830ff7960adf5249417778c9f158e7f918059
