### ISSUE TITLE
Using the web-based socket for HRI

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#141]
Could we integrate the code we used for the screen during `where is this?` into this repository? Or can we get a fork from the `RoboLand` repo? I think that visual information on the robot is super useful, and we are currently wasting the screen.

**Comment by robertocaiwu** [comment]
The one from roboland is very amy specific. I created a new repo on my git for the GO. I would need to clean it up and remove GO specific stuff. Also, we could develope it further and add more things.

Link to the repo: https://github.com/robertocaiwu/mas_web_interface

**Comment by PatrickNa** [comment]
Yes. I will create a repository for that and we start with what we have developed in Magdeburg, but should clean it and improve it quickly.

Suggestion from Alex and me regarding the repository name: `mas_hri_interface`

**Comment by argenos** [comment]
should we fork this one and start from there? or is it really better to start from scratch?

**Comment by PatrickNa** [comment]
Can we fork, but rename it? If yes, then we should do it. Otherwise I would prefer the more general name for the repository. In that case I would ask Roberto to push to the newly created repo and we continue the work from there.
