### ISSUE TITLE
[manipulation] move DMP parameters to a configuration file

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_domestic_robotics#158]
Currently, a lot of the parameters in `mdr_planning/mdr_actions/mdr_manipulation_actions/mdr_move_arm_action/ros/src/mdr_move_arm_action/dmp.py` are hardcoded. They should be moved into a configuration file.

**Comment by alex-mitrevski** [comment]
This issue was addressed by PR https://github.com/b-it-bots/mas_domestic_robotics/pull/192
