### ISSUE TITLE
Refactoring the picking and placing actions

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#170]
The following actions need to be rewritten to avoid code duplication:
* `mdr_behaviours/place.py`
* `mdr_behaviours/place_based_on_category.py`
* `mdr_place_action/action_states.py`
* `mdr_pickup_action/action_states.py`

See [here](https://sonarcloud.io/dashboard?id=mas_domestic_robotics) for more information.

**Comment by alex-mitrevski** [comment]
I wouldn't want to touch these at the moment since any refactoring has implications on the [action execution library](https://github.com/b-it-bots/action-execution) and the implementation of actions in general. I thus suggest we close this issue for the time being.
