### ISSUE TITLE
Clean up of the mas_hri_behaviours

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#171]
~~The current version of the package contains comments in the package.xml and CMakeLists.txt files.~~
These files also need to be updated to handle the dependencies correctly.

**Comment by argenos** [comment]
This also means moving the models to the [mas_models](https://github.com/b-it-bots/mas_models) repository.

**Comment by argenos** [comment]
Some clean up was already done in d3d0caa859633baaabd93582f2c7346a71a26cfc

**Comment by argenos** [comment]
@ErickKramer if you have some time this week, could you help out with this? Then we can finally merge #168

**Comment by ErickKramer** [comment]
Yes, I will work on this on Friday. @argenos
