### ISSUE TITLE
Clean up of where is this

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#174]
The rasa models we are loading are right now hard coded, see [this](https://github.com/b-it-bots/mas_domestic_robotics/blob/devel/mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/common/model/current/nlu/checkpoint) for an example. It probably makes sense to move the models to `mas_models` as well. 

@alex-mitrevski @minhnh thoughts?

**Comment by minhnh** [comment]
There's a [utility function](https://github.com/b-it-bots/mas_perception_libs/blob/055a1e44984dc829fc4b1ea4e03b81eb072e32f7/ros/src/mas_perception_libs/utils.py#L54) that may make it easier to get files from packages' relative paths. We can put these type of files in the model repository as a ROS package and access them this way.

**Comment by argenos** [comment]
Sounds good to me, can you open a PR for that?

**Comment by minhnh** [comment]
Do you mean to upload a model? Shouldn't @ErickKramer handle this?

**Comment by argenos** [comment]
I meant the utility function. Need a proposal on how to handle it, e.g. do we want to make `mas_models` dependent on `mas_perception_libs`?

**Comment by alex-mitrevski** [comment]
I don't think being dependent on `mas_perception_libs` makes sense in that context. It would be better if such utility functions are stored elsewhere, perhaps in a dedicated repository, since they could be useful in different places (e.g. we need something similar in the execution manager for handling the state machine hierarchies in the code rather than through launch files).

Edit: Perhaps we could create a repository similar to the [black-box-tools](https://github.com/ropod-project/black-box-tools) repository, which exposes a package with various useful functionalities - in that case, for working with MongoDB databases and black box data?

**Comment by minhnh** [comment]
I'm for a small utility repository for this kind small functionalities. We should try to keep it compact and as a single package though, to avoid another `mas_common_robotics`. `mas_utils`? `mas_tools`?

**Comment by argenos** [comment]
I’m in favor of that. Any preference on the name?

**Comment by alex-mitrevski** [comment]
I have a small preference for `mas_tools`, but only because I'm biased by `black-box-tools`. :)

**Comment by minhnh** [comment]
Either way is fine for me. I would also want to migrate some of the utilities from [`dataset_interface` repo](https://github.com/minhnh/dataset_interface/blob/feature/data_augmentation/utils.py) there for reuse.

**Comment by argenos** [comment]
Here it goes [mas_tools](https://github.com/b-it-bots/mas_tools)

**Comment by minhnh** [comment]
should it be a ROS package? I suppose there's the possibility for it to contain both C++ and Python.

**Comment by alex-mitrevski** [comment]
I'd say yes, mostly because ROS deals with package paths nicely.

**Comment by minhnh** [comment]
you can now access the function with `from mas_tools.ros_utils import get_package_path`

**Comment by argenos** [comment]
@ErickKramer do you have an estimated date on when you could push the fixes mentioned here? For now this seems to be one of the blocking issues for #168

**Comment by ErickKramer** [comment]
Yes, I'll get it done today.

**Comment by ErickKramer** [comment]
> The rasa models we are loading are right now hard coded, see [this](https://github.com/b-it-bots/mas_domestic_robotics/blob/devel/mdr_planning/mdr_scenarios/mdr_robocup_tasks/mdr_where_is_this/common/model/current/nlu/checkpoint) for an example. It probably makes sense to move the models to `mas_models` as well.
> 
> @alex-mitrevski @minhnh thoughts?

The checkpoint file is automatically generated by the training script of rasa. I am almost certain that it is not needed for the implementation part because it would've complained already when I put the model folder in lucy. 

@argenos should I just move everything the way it currently is inside  [mas_models](https://github.com/b-it-bots/mas_models) under a rasa_nlu/where_is_this folder?

**Comment by argenos** [comment]
Yes, but make it a ROS package, I would say: `rasa_nlu_models/common/where_is_this`. Then edit the `mdr_where_is_this` package to load the models from the right place.

**Comment by argenos** [comment]
@minhnh can give you further info on how to use the utilities from `mas_tools`

**Comment by alex-mitrevski** [comment]
Minh is at lunch at the moment, so I'll answer. Currently `mas_tools` only has a single script inside the package - [`ros_utils`](https://github.com/b-it-bots/mas_tools/blob/master/src/mas_tools/ros_utils.py), which exposes a single function, namely `get_package_path` (the documentation has an example call).

Basically, if `rasa_nlu_models` is a package, then you can find the absolute path of the model directory with the following code snippet:

```
from mas_tools.ros_utils import get_package_path
model_path = get_package_path('rasa_nlu_models', 'common', 'where_is_this')
```

**Comment by argenos** [comment]
Is this done? Was there a different PR for this issue other than the one that was closed?

**Comment by argenos** [comment]
@ErickKramer @alex-mitrevski shall I close this?

**Comment by alex-mitrevski** [comment]
Yeah, I think so.
