### ISSUE TITLE
Missing robot skills 

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#2]
- [ ] `open door` action for opening cupboards [10pts]
- [ ] `open door` action for opening door rooms [8pts]
- [x] `turn to` action [ 4pts] - see #3 
- [ ] `follow person`[7pts]
- [ ] `guide person` [10 pts]

**Comment by jcmayoral** [comment]
Are these still available?

**Comment by argenos** [comment]
Yes, but I'd suggest we first close #49

**Comment by jcmayoral** [comment]
On the guide person, what should be taken into account?

**Comment by minhnh** [comment]
I would suggest break this down into issues/projects and manage it with project boards

**Comment by argenos** [comment]
I will close this since these are not necessarily relevant anymore. The relevant skills need their own new issues.
