### ISSUE TITLE
Semantic mapping

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#28]
One example of such thing is [this](https://wiki.qut.edu.au/display/cyphy/Vision-based+Semantic+Mapping)

**Comment by argenos** [comment]
@whsu2s can you add a comment here with the things we discussed today as next steps? Thanks!

**Comment by whsu2s** [comment]
TODO: 
* Look for ROS packages that handle semantic mapping.
    - [https://github.com/fdayoub/ros-semantic-mapper](url)
    - [https://github.com/pronobis/rocs-ros](url)
* Understand the packages and how to use it.
