### ISSUE TITLE
Create a "turn to" action

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#3]
Create a `turn to` action using an actionlib wrapper with smach.
The robots should be able to turn X amount of degrees.

Inputs can be:
* degrees to turn
* another pose (calculate the difference between the robot and the pose)

**Comment by argenos** [comment]
@jcmayoral what do you say? I think this one has your name all over it.

**Comment by jcmayoral** [comment]
I will do it

**Comment by jcmayoral** [comment]
Can you assign it to me?

**Comment by argenos** [comment]
Related pull request: #24
