### ISSUE TITLE
Integrating Willlow Garage HRI Sound Library

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#4]
Worth 6 points.

Within the scope of this issue, is the creation of the node itself and the integration in a couple (or a few) of our components as an example (obviously, documentation as well). The audio files can be stored in a config folder and the meanings from a config file (pairing meaning to sound file). 
A few of the meanings I can foresee are:

- a greeting (correctly initialized, ready to move)
- started and finished planning (2 different sounds)
- Success or failure of actions (2 sounds) - although not sure about the granularity.
- An error occurred (something that needs manual recovery)
- Emergency stop
- sort of like a honk, to notify people to move away

It is very important that integrating to our codebase be easy. This might actually not necessarily be ros dependant but could behave sort of like the map server (depends on how you implement this). We should be able to turn sounds on and off during runtime (dynamic reconfigure). 
But most importantly: Playing the sounds is an extension, and should not hinder functionality.

**Comment by jcmayoral** [comment]
Hi. I was working on this today. In which folder should I add this functionality mdr_speech? or should I create one called mdr_tools?

**Comment by argenos** [comment]
Please create the metapackage mdr_hri, and add this package there
