### ISSUE TITLE
Turn the question matcher into an Answer action

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#47]
[This node](https://github.com/b-it-bots/mas_domestic_robotics/tree/kinetic/mdr_speech/mdr_question_matching) should be converted to an action server.

**Comment by argenos** [comment]
One big bug is the robot seems to answer every time recognizes something, even if it's not a question.

**Comment by sthoduka** [comment]
is this still an open issue? or is [this node](https://github.com/b-it-bots/mas_domestic_robotics/tree/kinetic/mdr_planning/mdr_actions/mdr_speech_actions/mdr_answer_action) a replacement?

**Comment by argenos** [comment]
I think it’s still open, we never got to integrate the two properly

**Comment by PatrickNa** [comment]
Since the pull request is through, I guess we could also close this one?

**Comment by argenos** [comment]
Yeah, go ahead, just mention your pull request here please
