### ISSUE TITLE
Updating repository.debs and rosinstall

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#5]
Both the migration to kinetic and to GitHub have affected this.

**Comment by alex-mitrevski** [comment]
This can be closed, right?

**Comment by moriarty** [comment]
;) it’s almost time to open one for 18.04 and Melodic

**Comment by alex-mitrevski** [comment]
I think that's unlikely to happen soon. We've only recently installed 16.04/Kinetic on Jenny and we need that setup for other projects as well.

I do want to start experimenting with Melodic on my machine though.

**Comment by argenos** [comment]
I’m thinking about this with the docker images already, hopefully we can set it up and use Travis already to tell us where efforts will be required.

Since migrations require time I’d say we can maybe think about it for next year, during the semester break.

@alex-mitrevski not yet, need to update the rosinstall file before closing it
