### ISSUE TITLE
Offline speech recognition

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#58]
Find an alternative to julius. 
Possible alternative: Pocket Sphinx

**Comment by oarriaga** [comment]
For speech to text offline recognition I have tried the deep speech from mozilla and it worked fairly well; however, some post-processing would be required since it's predicting letters and not by words:

https://github.com/mozilla/DeepSpeech

**Comment by jcmayoral** [comment]
I found this... I do not know if somebody has already experience with it https://github.com/cmusphinx/ros-pocketsphinx/tree/kinetic-devel

**Comment by alex-mitrevski** [comment]
Yeah, I think Patrick has already tried using pocketsphinx.

**Comment by argenos** [comment]
I've assigned @PatrickNa to mark it as "in progress", is there something we can start checking out as a pull request?

**Comment by PatrickNa** [comment]
I've implemented Pocketsphinx and tested it on my laptop. The results were pretty bad and nothing comparable to what we have seen in Magdeburg last time. Nevertheless I will refactor the code and test it on the Robot. Probably in the end of the week I can make a solid pull request.

**Comment by PatrickNa** [comment]
@robertocaiwu and I were already discussing on how to improve the model of pocketsphinx... However it was more brainstorming rather than concrete actions. We will intensify it in the next couple of weeks since it also effects RoboLand.

**Comment by PatrickNa** [comment]
I would say this can be closed or at least rephrased. We have offline speech recognition now, but it can be further improved.

**Comment by argenos** [comment]
@PatrickNa which pull request added it? Can you mention it here to document it? Otherwise I would keep it open until we have the code available

**Comment by PatrickNa** [comment]
Offline speech recognition is possible since bd730722c9e958deaed6c54247609ba60f7ccf3c (pull request 72). 
Specifically: PocketSphinx is used when no internet connection is available. Have a look at 
mas_domestic_robotics/mdr_speech/mdr_speech_recognition/ros/scripts/speech_recognizer for further details.

**Comment by argenos** [comment]
Good, we can close it. Not sure if I missed the documentation on how to setup pocketsphinx? I think we could open a new issue for that.

**Comment by PatrickNa** [comment]
Yes, we should continue open issues regarding speech.
