### ISSUE TITLE
mdr_2dnav launch files not working

### ISSUE THREAD

**Issue by jcmayoral** [b-it-bots/mas_domestic_robotics#62]
The launch files from the mdr_2dnav are not working. 2dnav.launch has some keys missing and the substitution $(find $(arg robot_pkg)) is not working and triggers an error (perhaps migration issues).

**Comment by alex-mitrevski** [comment]
I've just pushed fixes for this on `devel`.

**Comment by jcmayoral** [comment]
oh ok sorry
