### ISSUE TITLE
add requirements.txt to Python packages

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_domestic_robotics#66]
I propose adding `requirements.txt` to Python packages to handle Python dependencies. This will make maintaining dependencies modular to each package, which is easier than maintaining for the whole repository. We can start adding this to new packages and any packages with open pull requests.

**Comment by argenos** [comment]
What would be an example of a package with python dependencies that cannot be resolved with rosdep? 

My other concern would be that we would need a script to loop through all *.txt files for the CI if we do this package-wise.

**Comment by minhnh** [comment]
I don't think `pip` packages are all managed by `rosdep`. Some examples are `h5py`, `tf`, `keras`, and `pydmps` which I ran into the other day with the `move_arm` action.

Edit: I guess you can actually [specify system packages directly](http://docs.ros.org/jade/api/catkin/html/howto/format2/python_module_dependencies.html) so this is a no issue.
Edit 2: Actually system packages don't always include the necessary Python packages, i.e. `pydmps` can't be installed with `apt`. Also this allows specifying specific versions of the Python packages if needed.

**Comment by argenos** [comment]
I think rosdep actually supports pip. From their [documentation](http://docs.ros.org/independent/api/rosdep/html/commands.html#options):

```

  --as-root=INSTALLER_KEY:<bool>
                        Override whether sudo is used for a specific
                        installer, e.g. '--as-root pip:false' or '--as-root
                        "pip:no homebrew:yes"'. Can be specified multiple
                        times.

```

We should obviously test this, are you up for it?

**Comment by minhnh** [comment]
yeah I can look into it

**Comment by PatrickNa** [comment]
What is the status on this? I think this could be a possible solution for the installation of all speech relevant modules (e.g. PocketSphinx).

**Comment by argenos** [comment]
We need to try it out. Can you add the dependencies to the package.xml? I still believe the right way to do this is using rosdep

**Comment by argenos** [comment]
I will close this for now.
