### ISSUE TITLE
Implement "Double Metaphone" along with already implemented phonetic algorithms.

### ISSUE THREAD

**Issue by PatrickNa** [b-it-bots/mas_domestic_robotics#76]
"Double Metaphone" is another phonetic algorithm that can be used for speech matching. The idea of implementing another phonetic algorithm along with Levenshtein Distance is to have a counter check on the results.

## Context

After transforming the vocal input into text it needs to be analyzed further. Concretely this means, that it has to be compared to the known sentences in the database of the robot. The proposed algorithm is one option to do it efficiently. 

## Expected Behavior

Have another algorithm matching the speech input to questions or commands in the database. 

## Actual Behavior

Only the Levenshtein Distance analyzes the input so far. 

## Possible Fix

Python libraries with this algorithm exist. "Fuzzy" is one of them and can be used as a starting point.

**Comment by alex-mitrevski** [comment]
I'll close this since it's not high priority at the moment.
