### ISSUE TITLE
WIP: Placing unknown objects together

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#8]

**Comment by argenos** [comment]
@alex-mitrevski this was marked WIP, who should I assing?

**Comment by alex-mitrevski** [comment]
I'm sort of working on this, so I've assigned myself to it.

**Comment by alex-mitrevski** [comment]
This is done [here](https://github.com/b-it-bots/action-execution) - provided that the object recogniser can figure out that an object is unknown. I'll anyway close the issue.
