### ISSUE TITLE
Semantic/area-based navigation

### ISSUE THREAD

**Issue by alex-mitrevski** [b-it-bots/mas_domestic_robotics#81]
With our current grid-based navigation, we have no way of expressing any semantic information about the locations (e.g. we cannot send our robots go to the kitchen because we don't know where the kitchen is). This issue should be addressed as soon as possible so that we can perform purposeful navigation.

For a start, I suggest we start using a simple topological representation that allows us to express areas; in the long term, we could perhaps try to integrate the OSM-based navigation we are doing in the ROPOD project

**Comment by argenos** [comment]
I already have some code for this, so I'll make a pull request once I've dug it out and cleaned it up a bit

**Comment by argenos** [comment]
An initial version of this is being added in #145 from the [topological_map_ros](https://github.com/b-it-bots/topological_map) package
