### ISSUE TITLE
parametrize the recognition state in perceive plane action

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_domestic_robotics#97]
* sometimes we want to only detect and grasp any objects, so classifying (recognizing) is not wanted
* add launch or action goal parameter (preferred) to allow control of this behavior
* related to #91

**Comment by argenos** [comment]
@minhnh can this be closed?

**Comment by minhnh** [comment]
A solution was added in #145, but apparently is not working properly. I need to test on the robot. I will close once that's done.

**Comment by minhnh** [comment]
Fixed issue in launch file with 236ffd3. I will close this now.
