### ISSUE TITLE
generate templates for action servers and clients

### ISSUE THREAD

**Issue by minhnh** [b-it-bots/mas_domestic_robotics#98]
possible extensions to automatically generating other templates

**Comment by alex-mitrevski** [comment]
What do you mean by "templates?"

**Comment by minhnh** [comment]
I am not sure at the moment, since the code has changed quite a bit since February. Do we currently have abstractions for knowledge base interactions for the action clients and action servers?

**Comment by alex-mitrevski** [comment]
Obviously. The [action client base class](https://github.com/b-it-bots/mas_domestic_robotics/blob/devel/mdr_planning/mdr_rosplan_interface/ros/src/mdr_rosplan_interface/action_client_base.py) has an instance of the knowledge base interface (an instance to the ontology interface was also added during GO - currently on the `go-2019` branch). Is this what your questions is about?

The [action FTSM base class](https://github.com/b-it-bots/mas_execution_manager/blob/master/common/mas_execution/action_sm_base.py) currently doesn't include an instance of the KB/ontology interface, but I suppose they should be added there as well.

**Comment by minhnh** [comment]
Ok then the abstraction will be the templates then. I will close  this.
