### ISSUE TITLE
Integrating the dmp code into mas_domestic or mas_manipulation

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_domestic_robotics#99]

**Comment by minhnh** [comment]
@alex-mitrevski isn't this integrated already?

**Comment by alex-mitrevski** [comment]
Yeah, it is in the `move_arm` action. I'll thus close the issue.

**Comment by minhnh** [comment]
Could you also reference the related PR, commit, if any exist?

**Comment by alex-mitrevski** [comment]
https://github.com/b-it-bots/mas_domestic_robotics/pull/59
